added function that checks file status

diff --git a/Programs/Program1/matrix b/Programs/Program1/matrix
--- a/Programs/Program1/matrix
+++ b/Programs/Program1/matrix
@@ -86,21 +86,42 @@ function getMatrixAdMu(){
     fi
 }
 
+function _validateFile(){
+    # NAME
+
+    # SYNOPSIS
+
+    # DESCRIPTION
+
+
+    if [ ! -e "$1" ] # Check if file exists
+    then
+        echo "ERROR: '$1' does not exist." >&2
+        exit 4
+    elif [ ! -r "$1" ] # Check if file is readable
+    then
+        echo "ERROR: '$1' is not readable." >&2
+        exit 5
+    elif [ ! -s "$1" ] # Check if file is empty
+    then
+        echo "ERROR: '$1' is empty." >&2
+        exit 6
+    fi
+}
+
 function validateMatrix(){
     echo "TESTING validateMatrix"
 
-    echo "MATRIX CONTENTS:"
-    cat "$1"
-    echo ""
+    # echo "Going through each line"
+    # local lineNum=0
+    # while read line || [ -n "$line" ]
+    # do
+    #     ((++lineNum))
+    #     echo "Line $lineNum: $line"
+    # done < "$1"
+    # echo ""
 
-    echo "Going through each line"
-    local lineNum=0
-    while read line || [ -n "$line" ]
-    do
-        ((++lineNum))
-        echo "Line $lineNum: $line"
-    done < "$1"
-    echo ""
+    _validateFile "$1"
 }
 
 NUMARG=$#
